# Generated by Django 4.0.3 on 2022-04-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_villager_timeadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villager',
            name='CovidStatus',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('At Risk', 'At Risk')], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='villager',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
