# Generated by Django 4.0.3 on 2022-04-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_villager_covidstatus_alter_villager_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villager',
            name='CovidStatus',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('At Risk', 'At Risk')], default='Negative', max_length=10),
        ),
    ]
